snowflake_account              = "KIB31224"
snowflake_username             = "SHR1234"
snowflake_password             = "ASDWqwer1234@!"
snowflake_role                 = "ACCOUNTADMIN"
#snowflake_region               = "your_snowflake_region"
